spring:
  datasource:
      #使用hikari连接池
      hikari:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: admin
        max-total: 20
        max-idle: 8
        min-idle: 8
        initial-size: 10
        # 配置获取连接等待超时的时间
        max-wait-millis: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 60000
        #检测
        validation-query: SELECT 1
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        #打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-open-prepared-statements: 20

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
       dialect: org.hibernate.dialect.MySQL5Dialect

#日志记录
logging:
  file: log.log
  path: D://





